### ISSUE TITLE
Login does not work in the iOS app

### ISSUE THREAD

**Issue by radu-tutueanu** [realm-demos/realm-tasks#401]
Building the latest master and using the iOS simulator, the app claims it cannot connect to the server when you try to login.
If you downgrade RealmLoginKit to 0.0.9, the app can connect just fine.

cc @TimOliver @stel

**Comment by TimOliver** [comment]
Uh-oh. That might be a glitch caused by the PR that added HTTPS support to it.

What was the exact URL that was being provided to the login controller?

**Comment by radu-tutueanu** [comment]
I'm not entirely sure, my guess is `http://${ip}:9080/auth`

**Comment by TimOliver** [comment]
Ahh okay. I discovered the issue and fixed it in https://github.com/realm-demos/realm-loginkit/pull/29

I just pushed the build to CocoaPods (0.0.12), so that should fix this issue. :)

**Comment by janicechau12** [comment]
Hi Tim, I tried to sign up and login to your RealmTasks iOS app but I am not able to. It keeps on showing me "Could not connect to server" error message. Please help ..
![simulator screen shot - iphone 8 plus - 2017-11-04 at 10 52 08](https://user-images.githubusercontent.com/8206974/32401680-036dc1f6-c14f-11e7-98ef-d4903ffaf3db.png)

**Comment by TimOliver** [comment]
Hi @janicechau12! You need to have an instance of Realm Object Server running on your same local machine. Realm Tasks internally generates the IP address of that machine and assumes that is the target server.

I hope that helps!

**Comment by TimOliver** [comment]
This issue is really old, so if there are any more issues of a similar nature, it might be more appropriate to open a new issue in order to follow the conversation more clearly. Thanks! :)
