### ISSUE TITLE
Google Auth doesn't work: Status{statusCode=unknown status code: 12501, resolution=null}

### ISSUE THREAD

**Issue by Zhuinden** [realm-demos/realm-tasks#410]
`handleSignInResult` receives a `GoogleSignInResult` where `isSuccess()` == `false`.

The status has following message:

`Status{statusCode=unknown status code: 12501, resolution=null}`

I'm not sure what's wrong with it at the moment.

**Comment by Zhuinden** [comment]
It probably has something to do with the included debug.keystore and its SHA1 hash or something.

**Comment by andysmithdev** [comment]
How did you fix this problem please?
I'm a little surprised the demo app doesn't work out of the box, very disappointing.

**Comment by Zhuinden** [comment]
@andysmithdev I think you need to create a release build for it to use the provided keystore as the signing config
